version: '3.8'

services:
  vereto-mc:
    image: itzg/minecraft-server:java8-multiarch
    volumes:
    - ./data:/data
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      MEMORY: 8G
      TYPE: FORGE
      VERSION: 1.16.5
      FORGEVERSION: 36.2.35
      # Need to download Server-Files-0.4.13.zip and
      # put it in modpacks directory next to this compose file
      GENERIC_PACK: /modpacks/ATM6-1.8.27-server.zip
      # server.properties
      SERVER_NAME: "Vereto Minecraft Server"
      MOTD: "Welcome to the Vereto ATM6 minecraft server."
      DIFFICULTY: "hard"
      OPS: "593fc401-08ee-4f5f-8716-e46edd1f5a00"
      MAX_PLAYERS: "50"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      MAX_TICK_TIME: "-1"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "12"
      MODE: "survival"
      PVP: "false"
      LEVEL_TYPE: "terraforged"
      SEED: "855839043"
      LEVEL: "Vereto World"
      ALLOW_FLIGHT: "true"
      ONLINE_MODE: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "somePassword"
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
